Hw2
starkda/java-course-2023-backend-template pull request #2
Opened 2024-02-25 19:16 UTC by starkda

2024-02-28 19:42 UTC, IvanAksenov11 requested changes
нужно поправить замечания

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +public class ApplicationConfig {
для этих вещей лучше писать отдельные конфиги

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/main/java/edu/java/configuration/Github.java
> +public class Github {
я бы сделал приватные поля

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/main/java/edu/java/configuration/Stackoverflow.java
> +public class Stackoverflow {
я бы сделал приватные поля

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/main/java/edu/java/configuration/StackOverflowClient.java
мне кажется, этому классу не место в пакете configuration. Лучше завести пакет client  и складывать туда все клиенты

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/main/java/edu/java/configuration/GithubRepositoryClient.java
тоже убрал бы в другой пакет

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/main/java/edu/java/dto/SiteUrl.java
> +@Data
Смотри, ты поставил аннотацию @Data, которая несет за собой кучу функционала. При этом у тебя в классе единственное поле публичное, которое еще и final. И плюс к этому ты явно переопределяешь toString();
Рекомендую почитать про @Data вот тут https://projectlombok.org/features/Data, понять, что именно из предлагаемого функционала тебе нужно и воспользоваться только им.

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/main/java/edu/java/dto/StackoverflowResponse.java
> +
лишние строки

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/main/resources/application.yml
> -    force-check-delay: 10s
шедулер решил убрать?

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/main/java/edu/java/configuration/GithubRepositoryClient.java
> +        String kek = webClient.get()
странное название для переменной

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/test/java/edu/java/scrapper/StackoverflowClientTest.java
> +        Assertions.assertThat(stackOverflowClient.fetchAnswersInfo(new SiteUrl(
кажется, название теста не совпадает с тем, что в нем реально проверяется

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/test/resources/it/githubRepositoryResponseBody
тестовые данные слишком большие. Можно спокойно выкинуть лишние поля, тем более учитывая, что в тесте проверяется один параметр судя по всему

2024-02-28 19:42 UTC, IvanAksenov11 commented on scrapper/src/test/resources/it/stackoverflowResponseBody
то же самое касается этого файла

2024-03-03 15:37 UTC, starkda commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +public class ApplicationConfig {
пофиксил

2024-03-03 15:40 UTC, starkda commented on scrapper/src/main/java/edu/java/configuration/Github.java
> +public class Github {
пофиксил. мне кажется нужно запретить вообще впринципе как-либо изменять состояние кофиг-класса, но чтобы не тратить время на переписывание тестов, я добавил сеттеры на класс

2024-03-03 15:41 UTC, starkda commented on scrapper/src/main/java/edu/java/dto/SiteUrl.java
> +@Data
Заменил на Value

2024-03-03 15:41 UTC, starkda commented on scrapper/src/main/resources/application.yml
> -    force-check-delay: 10s
вернул в родную гавань

2024-03-03 15:41 UTC, starkda commented on scrapper/src/test/java/edu/java/scrapper/StackoverflowClientTest.java
> +        Assertions.assertThat(stackOverflowClient.fetchAnswersInfo(new SiteUrl(
пофиксил

2024-03-03 15:42 UTC, starkda commented on scrapper/src/test/resources/it/githubRepositoryResponseBody
все ненужное выкинул

2024-03-03 15:45 UTC, starkda commented
@IvanAksenov11 добавил шедулер.
Я продублирую это сообщение еще на платформе:
Можно пожалуйста продлить мне дедлайн по 3 домашке? У меня в универе сейчас дедлайн на дедлайне, никак не успею сделать(

2024-03-04 12:51 UTC, IvanAksenov11 approved these changes

2024-03-06 12:35 UTC, merged